// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0v-yPc8LV0lFdS9mSJ2nFwAdVXyffzzU',
    appId: '1:370140466505:web:a25f379ac90fc49cbf1e98',
    messagingSenderId: '370140466505',
    projectId: 'train-transit-80580',
    authDomain: 'train-transit-80580.firebaseapp.com',
    storageBucket: 'train-transit-80580.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Cmu-rdMrlcH6h5GVD1Kwb6UKNKK__pQ',
    appId: '1:370140466505:android:a906daea966cca9fbf1e98',
    messagingSenderId: '370140466505',
    projectId: 'train-transit-80580',
    storageBucket: 'train-transit-80580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEIUptNKHcC1Y_IgMiGEVjDgPbBESNUuA',
    appId: '1:370140466505:ios:eefbd451ee5a5c63bf1e98',
    messagingSenderId: '370140466505',
    projectId: 'train-transit-80580',
    storageBucket: 'train-transit-80580.appspot.com',
    iosBundleId: 'com.example.trainTransit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEIUptNKHcC1Y_IgMiGEVjDgPbBESNUuA',
    appId: '1:370140466505:ios:eefbd451ee5a5c63bf1e98',
    messagingSenderId: '370140466505',
    projectId: 'train-transit-80580',
    storageBucket: 'train-transit-80580.appspot.com',
    iosBundleId: 'com.example.trainTransit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0v-yPc8LV0lFdS9mSJ2nFwAdVXyffzzU',
    appId: '1:370140466505:web:c30768274585d4d1bf1e98',
    messagingSenderId: '370140466505',
    projectId: 'train-transit-80580',
    authDomain: 'train-transit-80580.firebaseapp.com',
    storageBucket: 'train-transit-80580.appspot.com',
  );
}
