
List<List<String>> trainStationsCombinations = [
  // Chennai to Madurai
  ['Chennai Egmore', 'Tambaram', 'Chengalpattu Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Tambaram', 'Chengalpattu Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Tambaram', 'Chengalpattu Junction', 'Villupuram Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Tambaram', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Tambaram', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Tambaram', 'Villupuram Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Tambaram', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Tambaram', 'Tiruchirappalli Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Villupuram Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Chengalpattu Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Chengalpattu Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Chengalpattu Junction', 'Villupuram Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Chengalpattu Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Chengalpattu Junction', 'Tiruchirappalli Junction', 'Madurai Junction'],
  ['Chennai Egmore', 'Chengalpattu Junction', 'Dindigul Junction', 'Madurai Junction'],

  // Madurai to Chennai
  ['Madurai Junction', 'Dindigul Junction', 'Tiruchirappalli Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Tiruchirappalli Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Tiruchirappalli Junction', 'Villupuram Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Tiruchirappalli Junction', 'Chengalpattu Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Tiruchirappalli Junction', 'Chengalpattu Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Dindigul Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Chengalpattu Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Chengalpattu Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Villupuram Junction', 'Dindigul Junction', 'Chengalpattu Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Villupuram Junction', 'Dindigul Junction', 'Chengalpattu Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Villupuram Junction', 'Chengalpattu Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Chengalpattu Junction', 'Villupuram Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Tiruchirappalli Junction', 'Chengalpattu Junction', 'Villupuram Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Chengalpattu Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Chengalpattu Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Chengalpattu Junction', 'Villupuram Junction', 'Tiruchirappalli Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Chengalpattu Junction', 'Villupuram Junction', 'Dindigul Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Chengalpattu Junction', 'Villupuram Junction', 'Dindigul Junction', 'Chennai Egmore'],
  ['Madurai Junction', 'Chengalpattu Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Tambaram', 'Chennai Egmore'],
  ['Madurai Junction', 'Chengalpattu Junction', 'Tiruchirappalli Junction', 'Dindigul Junction', 'Chennai Egmore'],
];
